server:
  port: 12001
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    hikari:
      username: sa
      jdbc-url: jdbc:h2:file:./h2db/db/data;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1

